---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: docker.io/pain13/webapp:newTag
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 300
            successThreshold: 1
            timeoutSeconds: 300
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
  namespace: webapp
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: webapp
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20